In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('covid_toy.csv')

In [3]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder , OrdinalEncoder

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split 
X_train ,X_test , y_train ,y_test = train_test_split(df.drop(columns=['has_covid']) , df['has_covid'] ,test_size= 0.2 , random_state= 42)

In [8]:
X_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
..  ...     ...    ...     ...        ...
60   24  Female  102.0  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
92   82  Female  102.0  Strong    Kolkata
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

Using Different imputing technique

In [13]:
# Adding simple imputer to fever col 
si = SimpleImputer()
x_train_fever = si.fit_transform(X_train[['fever']])

# test data
x_test_fever = si.transform(X_test[['fever']])

x_train_fever.shape

(80, 1)

In [19]:
# ordinal encoding
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

X_test_cough = oe.transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [22]:
# one hot enocodig 
ohe = OneHotEncoder(drop='first',sparse_output= False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

X_test_gender_city = ohe.transform(X_test[['gender' ,'city']])

X_test_gender_city.shape

(20, 4)

In [28]:
# Extracting Age 
X_train_age = X_train.drop(columns = ['gender' , 'fever' , 'cough' , 'city']).values
X_test_age = X_test.drop(columns = ['gender' , 'fever' , 'cough' , 'city']).values
X_train_age.shape

(80, 1)

In [32]:
X_train_transformed = np.concatenate((X_train_age,x_train_fever,X_train_gender_city,X_train_cough ), axis=1)

X_test_transfromed = np.concatenate((X_test_age,x_test_fever,X_test_gender_city,X_test_cough ), axis = 1)

X_train_transformed.shape

(80, 7)

Column Transformer

In [33]:
from sklearn.compose import ColumnTransformer

In [34]:
ct = ColumnTransformer(transformers=[
    ('tn1' , SimpleImputer(),['fever']),
    ('tn2' , OrdinalEncoder(categories=[["Mild","Strong"]]) , ['cough']),
    ('tn3' , OneHotEncoder(drop='first' , sparse_output= False) ,['gender' , 'city'])
] , remainder='passthrough')

In [36]:
ct.fit_transform(X_train).shape

(80, 7)

In [38]:
ct.transform(X_test).shape

(20, 7)